apiVersion: v1
kind: Secret
metadata:
  name: private-secret
  namespace: argocd 
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://gitlab.com/tdc4/deployments/deployment-argocd-mgmt-west-platform.git
  password: JXszNSufP6YrYqhWbEGv
  username: gitlab+deploy-token-3494647
